"""
mage_tool
---------

mage_tool is a library and an executable used to create oligonucleotides for
use in multiplex automated genome engineering (MAGE) experiments.

"""

import os
import sys
import subprocess
from setuptools import setup


# Fetch version from git tags, and write to version.py.
# Also, when git is not available (PyPi package), use stored version.py.
version_py = os.path.join(os.path.dirname(__file__), 'mage_tool', 'version.py')

try:
    version_git = subprocess.check_output(["git", "describe"]).rstrip()
except subprocess.CalledProcessError:
    with open(version_py, 'r') as fh:
        version_git = open(version_py).read().strip().split('=')[-1].replace('"','')

version_msg = "# Do not edit this file, pipeline versioning is governed by git tags"
with open(version_py, 'w') as fh:
    fh.write(version_msg + os.linesep)
    fh.write("__version__='" + str(version_git) + "'\n")

setup(
    name='mage_tool',
    version='{ver}'.format(ver=version_git),
    url='modest.ntz.nu',
    license='Proprietary',
    author='Mads Valdemar Anderson, Michael Schantz Klausen',
    author_email='mskl@cbs.dtu.dk',
    description='A tool to automatically and easily create oligonucleotides for MAGE',
    long_description=__doc__,
    packages=['mage_tool', 'mage_tool.operations'],
    include_package_data=True,
    zip_safe=False,
    platforms='any',
    install_requires=[
        'biopython>=1.61',
        'pdfrw>=0.1',
        'PyYAML>=3.10',
        'matplotlib>=1.2.1',
        'reportlab>=2.7',
    ],
    scripts=[
        "MODEST.py",
        "MODEST_csv2report.py",
        "MODEST_genecheck.py",
        "MODEST_mkgbcfg.py",
    ]
)
